### ISSUE TITLE
电脑没有Path项

### ISSUE THREAD

**Issue by ghost** [xausky/DockerRegisterCloud#1]
电脑环境变量里并没有B站视频里的那个Path项，怎么搞？
![QQ截图20200510174437](https://user-images.githubusercontent.com/63418154/81495852-ef68a480-92e5-11ea-9eab-eb42fe31524a.png)

**Comment by xausky** [comment]
用户变量里面没有系统变量里面有，或者搜索一下，Win7 PATH 环境变量
