### ISSUE TITLE
上传无法进行

### ISSUE THREAD

**Issue by ghost** [xausky/DockerRegisterCloud#2]
上传的时候写完文件名或者写完相对路径，都无法上传，出现一大堆代码，有点伤脑筋诶
![QQ截图20200510185617](https://user-images.githubusercontent.com/63418154/81497908-39588700-92f4-11ea-96c6-0ffe977aa90b.png)

**Comment by xausky** [comment]
贴图，或者贴大堆代码

**Comment by ghost** [comment]
就这些，窗口无法扩大，应该没有遗漏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xausky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月10日(星期天) 晚上9:43
收件人:&nbsp;"xausky/DockerRegisterCloud"<DockerRegisterCloud@noreply.github.com&gt;;
抄送:&nbsp;"Tom"<easygame@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xausky/DockerRegisterCloud] 上传无法进行 (#2)





 
贴图，或者贴大堆代码

**Comment by xausky** [comment]
刚刚没加载，这个错误应该是账号密码错误，可以确认一下然后重新 Login

**Comment by ghost** [comment]
好的，我试一下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xausky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月10日(星期天) 晚上9:57
收件人:&nbsp;"xausky/DockerRegisterCloud"<DockerRegisterCloud@noreply.github.com&gt;;
抄送:&nbsp;"Tom"<easygame@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xausky/DockerRegisterCloud] 上传无法进行 (#2)





 
刚刚没加载，这个错误应该是账号密码错误，可以确认一下然后重新 Login

**Comment by xausky** [comment]
刚刚没加载，这个错误应该是账号密码错误，可以确认一下然后重新 Login

**Comment by ghost** [comment]
账号密码是我在阿里云登录过得，试了几次，没问题，但是到软件里就不行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xausky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月10日(星期天) 晚上9:57
收件人:&nbsp;"xausky/DockerRegisterCloud"<DockerRegisterCloud@noreply.github.com&gt;;
抄送:&nbsp;"Tom"<easygame@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xausky/DockerRegisterCloud] 上传无法进行 (#2)





 
刚刚没加载，这个错误应该是账号密码错误，可以确认一下然后重新 Login

**Comment by xausky** [comment]
阿里云的仓库密码并不是登录密码，是开通容器仓库服务时候设置的密码，不行可以重置一下。

**Comment by ghost** [comment]
OK了，谢谢，视频里没演示到，没设置的应该都是我这个问题，估计别人应该也不知道吧这个吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xausky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月10日(星期天) 晚上11:05
收件人:&nbsp;"xausky/DockerRegisterCloud"<DockerRegisterCloud@noreply.github.com&gt;;
抄送:&nbsp;"Tom"<easygame@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xausky/DockerRegisterCloud] 上传无法进行 (#2)





 
阿里云的仓库密码并不是登录密码，是开通容器仓库服务时候设置的密码，不行可以重置一下。

**Comment by xausky** [comment]
我在视频简介说明一下，谢谢反馈

**Comment by wuzhumeng** [comment]
> 阿里云的仓库密码并不是登录密码，是开通容器仓库服务时候设置的密码，不行可以重置一下。

请问如何修改开通容器仓库服务时候设置的密码？
