### ISSUE TITLE
请问可以适配VPS

### ISSUE THREAD

**Issue by Seeger0216** [xausky/DockerRegisterCloud#23]
想用vps做一些分享，希望可以出一个vps上面的版本。最好能支持默认仓库，打开就能用，但是不给上传权限。谢谢大佬。尝试过用阿里云函数包里面的东西部署到vps，但是只有html界面，无法连接到仓库，更别说登陆了，应该是哪里出问题了。

**Comment by xausky** [comment]
函数包里面的东西可以部署到 linux x64 的服务器上，运行里面的 bootstrap 可执行文件部署
