### ISSUE TITLE
arm架构不能运行

### ISSUE THREAD

**Issue by centful** [xausky/DockerRegisterCloud#26]
我在arm架构设备上运行不了，是否还没适配arm架构呢还是我的使用方法有问题？如果是未适配，可否适配一下呢？谢谢

**Comment by xausky** [comment]
只有 安卓 支持 ARM 架构，其他的均只支持 amd64 架构

**Comment by xausky** [comment]
是有在树莓派或者其他 arm 服务器端使用的需求么

**Comment by centful** [comment]
是的呀

**Comment by xausky** [comment]
这个因为现在 Github Action 提供的编译环境也没有 ARM，而且 Dart 又不支持交叉编译，暂时不进行支持，需要可以自行下载源码到树莓派编译
