### ISSUE TITLE
web 端设置默认仓库地址

### ISSUE THREAD

**Issue by loveqianool** [xausky/DockerRegisterCloud#30]
现在发给别人下载多个文件还要给他说怎么设置仓库地址，有点繁琐。

**Comment by xqymain** [comment]
修改lib/app.dart中currentRepository的初始化值即可。
`@JsonSerializable()
class GlobalConfig {
  String userAgent = "Docker-Client/20.10.3-ce (linux)";
  String currentRepository = "ccr.ccs.tencentyun.com/srvpub/main";  // Default Repository setting
  Map<String, String> repositoryCretificates = Map();

  GlobalConfig();

  factory GlobalConfig.fromJson(Map<String, dynamic> json) =>
      _$GlobalConfigFromJson(json);
  Map<String, dynamic> toJson() => _$GlobalConfigToJson(this);
}`

**Comment by loveqianool** [comment]
谢谢你，请问能否通过设置环境变量修改呢？

**Comment by xausky** [comment]
> 谢谢你，请问能否通过设置环境变量修改呢？

把值写成 `Platform.environment["REPO"]` 这样即可

**Comment by loveqianool** [comment]
> > 谢谢你，请问能否通过设置环境变量修改呢？
> 
> 把值写成 `Platform.environment["REPO"]` 这样即可

能不能内置这个功能呀，我在 docker 内找不到这个文件。
