### ISSUE TITLE
跨仓库文件分享存储需求讨论

### ISSUE THREAD

**Issue by xausky** [xausky/DockerRegisterCloud#4]
这个功能的实现有相应的机制，但是有如下限制：
1. 接受分享的仓库必须与被分享仓库使用同一个仓库服务商和区域
2. 被分享的仓库必须是公开访问权限或者与分享的仓库使用同一认证账号

不知道大家对这个功能在以上两个限制下有多大需求

**Comment by cexll** [comment]
现目前对这个功能应该需求不大
1. 希望能把Web端的完善一下 
2. 希望登录这个功能重新设计一下，点击登录 输入地址，然后输入账号密码（旁边加个获取账号密码教程？类似）
3. 文件上传下载这方面，比如能上传文件夹（批量上传文件/批量上传文件夹内的文件）

**Comment by xausky** [comment]
需求不高，暂时不打算实现了，如有需求可以再次打开
