### ISSUE TITLE
新的cli交互方式

### ISSUE THREAD

**Issue by Borber** [xausky/DockerRegisterCloud#42]
有没有考虑更改一下cli的交互方式

类似baidu-psc的那种 有软件自己的目录结构以及补全的呀? 那种体验真的不错,  以及设置默认的下载路径

**Comment by xausky** [comment]
常规使用还是用 GUI 吧，baidu-pcs 那个是因为官方本身没有 GUI 支持，这个项目的 cli 主要是用于写脚本进行批处理的。
