### ISSUE TITLE
用阿里的最近有没有被限速呀? 

### ISSUE THREAD

**Issue by Borber** [xausky/DockerRegisterCloud#43]
我这边下载卡在140k左右了

![image](https://user-images.githubusercontent.com/30563826/109926215-ac0c7600-7cfd-11eb-88a1-a24f241ae773.png)

**Comment by xausky** [comment]
是的，内容检测，gz 压缩后可绕过。

**Comment by Borber** [comment]
> 是的，内容检测，gz 压缩后可绕过。

那请问现在用什么会比较好一点? 不想每次都要压缩上传 或者增加压缩上传的功能吗?

**Comment by xausky** [comment]
> > 是的，内容检测，gz 压缩后可绕过。
> 
> 那请问现在用什么会比较好一点? 不想每次都要压缩上传 或者增加压缩上传的功能吗?

本项目不会做任何针对某个仓库的修改，压缩上传会导致直接下载功能失效并且也不是协议的标准内容，哪个仓库好可以自己多试试。
