### ISSUE TITLE
Up主脑洞值得学习！！但是不是已经被阿里发现了，下载怎么不到200K。

### ISSUE THREAD

**Issue by coloraven** [xausky/DockerRegisterCloud#48]
是不是已经被阿里发现了，现在下载只有不到200K了，正常我这里下载有4M/s，上传倒是可以有1+M（带宽有10M上传）
![image](https://user-images.githubusercontent.com/5030800/115339387-4275f780-a1d7-11eb-955e-8d415ee8dfff.png)

**Comment by xausky** [comment]
是基于内容检测的限制，gz 格式的文件无限制，本项目不会修改

**Comment by Borber** [comment]
现在就算是 gz 格式 阿里也会限速了, emmm 感觉得黄啊
