### ISSUE TITLE
华为云生成的直连不出几分钟就到期

### ISSUE THREAD

**Issue by e9965** [xausky/DockerRegisterCloud#57]
?x-amz-security-token=gQ5hcC1zb3V0aGVhc3QtMY6SNS8U1vpsmODgSFN1rFX_Go0x36LtS202T3vYWzjn9xpp4Tv6U8ho3c69oD7YgBG5Ecnmwg5fufjDnRt5YoW1wqeWv_Nt9TXTKGiM1Qtr-NqWfHN_xk5tlB9mc7ihKPZgIppdSjBh9KI-6PF0oSyN-iies9VIz_oCzlJP9rvicBYr2HzQwe_VhKhFCn3pWG4bx1KoKOgKokKJEq3E6gnoSfpU9qxs9iBcF-NDJK53TR9qEUPbk9ofx7PKcrDO5KGVlATbxKS3cpOWNCfXRZIOlw3Z73r2kf4TRpA_tHNw3gmnX15xVFZoR1iQJq76iTjke19fMqdI0zpcn2R3NnMqbM9M45UkYiAh4z4cxlxyM9AOQWpzKaV9kN03mf-iDgOYF6gVoXCAIMzEwbiGroFbfjUYkPUv9_zNJ30f8e_h4h5yxQjnu5dwnEGF_1ZxuVcFo_-cP8sBR_FdGjJF4lSHfP6mI_GucbgdwzdADzZolVcYSWZHMZnoYxtSU9KFt1J1OSH2FUnOKIUQ5SuRgNd3UBKgwmlF2_RYD2ZVjjcroe-xiafkYivSvxFuHOF2fG_x6rcjkNJL9VeOtFZLaf2kyx6JIVviBm53kc_FvZVhLCZnPRYuZ0L2kypiutq-yWMgit8MGPOIplkab8fW7VUkmpSCNkIOSgWybcqya5TLgIluwHETnhWxkex5Bl41hQGkkdzvMD0Kamzu_wT2LvGsZR8v7KP9e82CtuN2eZZ1wd_MEv60Q23yGgdX3Xg3i8NyCjiNtHJBidUoI8JHHt5525LSpQ58QGQzRI_IO0q1Tg%3D%3D&AWSAccessKeyId=T88T22XL7BGPJV6UXF2F

**Comment by xausky** [comment]
直链过期时间不受本项目控制，请加大网速下载或者选择其他厂商服务。
