### ISSUE TITLE
登录时出错

### ISSUE THREAD

**Issue by Jai-wei** [xausky/DockerRegisterCloud#6]
F:\桌面>drc login registry.cn-beijing.aliyuncs.com/jaiwei/traindata
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []()
#0      _$GlobalConfigFromJson (package:docker_register_cloud/app.g.dart:11)
#1      new GlobalConfig.fromJson (package:docker_register_cloud/app.dart:36)
#2      main (file:///d:/a/dockerregistercloud/dockerregistercloud/bin/drc.dart:12)
#3      _RootZone.runUnary (dart:async/zone.dart:1439)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711)
#7      Future._completeWithValue (dart:async/future_impl.dart:526)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298)
#10     BasePlatform.load (package:docker_register_cloud/app.dart:0)
#11     _RootZone.runUnary (dart:async/zone.dart:1439)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711)
#15     Future._completeWithValue (dart:async/future_impl.dart:526)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169)

**Comment by xausky** [comment]
使用的是哪个版本的命令行程序

**Comment by Jai-wei** [comment]
> 使用的是哪个版本的命令行程序

win10命令行

**Comment by Jai-wei** [comment]
> > 使用的是哪个版本的命令行程序
> 
> win10命令行

linux上登录时也有相同的错误

**Comment by xausky** [comment]
版本是 v1.3.1 么

**Comment by Jai-wei** [comment]
> 版本是 v1.3.1 么

是的

**Comment by xausky** [comment]
https://lanzous.com/b0e7ult4b 这里修复了
