### ISSUE TITLE
Drcd Web端口Bug报告反馈

### ISSUE THREAD

**Issue by Skyler2020** [xausky/DockerRegisterCloud#7]
DOCKER REGISTER CLOUD WEB BUG REPORT
drcd Bug反馈报告 2020/06/05 FRI
一、本次测试涉及机型：
1.Apple iPhone7 128G ZP/A iOS12.3.1
2.Apple iPhone Xs Max 512G ZP/A iOS12.0
3.Apple iPad 第六代 （iPad2018）128G CH/A iOS12.1.3
4.OPPO Find X 兰博基尼版 512G 新加坡版 CPH1875 ColorOS9（基于Android9）
5.ASUS 飞行堡垒 FX95GU9750 国行 512G 镁光2200V 16G_DDR4_2666双通道 基于Win10专业版1903
6.ASUS 飞行堡垒 FX80GM8750 国行 256G 三星PM981 8G_DDR4_2666双通道 基于Win10专业版 1803

二、涉及Web 版本
1.2.0 1.3.0 1.3.1 1.3.2
均使用docker部署

三、部署过程
docker pull xausky/drcd:v1.3.2 #镜像拉取命令
docker images #查看镜像ID
docker run -d -p 3000:3000 镜像ID #此处”:”前指本地服务端口，后为映射(访问该服务端口)此处为3000
docker ps #查看运行情况

四、部署挂载镜像机型
东芝Satellite C40A 480G(低级格式化后)HDD原装东芝SATA2 2G_DDR3_1333 Centos8_x86_64 带GNOME桌面 Intel赛扬1005M 高清核芯显卡

五、发现以下Bug
1.在被测1号机型中的 Safari浏览器中打开该站点无法进行任何操作。只能看到画面。
-建议原因：可能不支持Go语言和Floppy。

2.在被测1号和2号和3号机型机型中的Safari、X5内核、Google Chrome浏览器、百度 浏览器无法正常获取仓库内文件临时链接。具体症状为点击获取链接按钮后提示成功但实际没有成功。

其余机型暂未发现问题。

六、结论
Apple iOS端 iOS12系列 的产品无法正常使用。

测试Web端地址 http://docker.leeskyler.top:3000

**Comment by xausky** [comment]
问题应该都是 iOS 系统对 Flutter 的支持问题，包括第三方浏览器也有限制，后面我看看能不能适配一下。

**Comment by xausky** [comment]
后续报告升级 iOS 新版本版本可以解决这个问题
