### ISSUE TITLE
建议-希望增加文件SHA256复制功能

### ISSUE THREAD

**Issue by Skyler2020** [xausky/DockerRegisterCloud#8]
理由:
1.上传或下载镜像后能够校验SHA256是否变更
2.分享链接时方便

虽然能在临时链接中提取到，但是手动复制极其不方便。
希望能够考虑，谢谢

**Comment by xausky** [comment]
很少出现成功但是下载文件 SHA256 不匹配的情况，况且大部分文件有自校验，暂不实现了
